---

-
  name: Add nginx APT repository
  apt_repository:
    repo: 'ppa:nginx/stable'
    state: present
    update_cache: yes

-
  name: Install nginx-extras
  apt:
    name: nginx-extras
    state: latest
    update_cache: yes
    dpkg_options: 'force-confdef,force-confold'

-
  name: Prepare vhost config directory
  file:
    path: "{{ nginx_vhost_config_root }}"
    owner: root
    group: root
    recurse: yes
    state: directory

-
  name: Prepare inc config directory
  file:
    path: "{{ nginx_inc_config_root }}"
    owner: root
    group: root
    recurse: yes
    state: directory

-
  name: Prepare passwd config directory
  file:
    path: "{{ nginx_config_root }}"
    owner: root
    group: root
    recurse: yes
    state: directory

-
  name: Install Python passlib for htpasswd module
  apt:
    name: python-passlib

-
  name: Prepare htpasswd
  htpasswd:
    name: "{{ kibana_basic_auth_user }}"
    password: "{{ kibana_basic_auth_password }}"
    path: /etc/nginx/passwd/kibana.htpasswd
    state: present

-
  name: Install log_format_ltsv.nginx.conf
  copy:
    dest: "{{ nginx_inc_config_root }}/log_format_ltsv.nginx.conf"
    src: log_format_ltsv.nginx.conf
    owner: root
    group: root
  notify:
    - Reload nginx

-
  name: Install nginx.conf
  template:
    dest: "{{ nginx_config_root }}/nginx.conf"
    src: nginx.conf.j2
    owner: root
    group: root
  notify:
    - Reload nginx

-
  name: Install default host conf
  template:
    dest: "{{ nginx_vhost_config_root }}/default.nginx.conf"
    src: default.nginx.conf.j2
    owner: root
    group: root
  notify:
    - Reload nginx

-
  name: Install els host conf
  template:
    dest: "{{ nginx_vhost_config_root }}/els.nginx.conf"
    src: els.nginx.conf.j2
    owner: root
    group: root
  notify:
    - Reload nginx

-
  name: Start nginx
  service:
    name: nginx
    state: started
