---

-
  name: Import Mackerel GPG key
  apt_key:
    url: https://mackerel.io/assets/files/GPG-KEY-mackerel
    state: present

-
  name: Add Mackerel repository
  apt_repository:
    repo: 'deb http://apt.mackerel.io/debian/ mackerel contrib'
    state: present
    update_cache: yes

-
  name: Install mackerel-agent
  apt:
    name: mackerel-agent
    state: latest
    update_cache: yes
    dpkg_options: 'force-confdef,force-confold'
  notify:
    - Restart mackerel-agent

-
  name: Install mackerel-agent config
  template:
    dest: /etc/mackerel-agent/mackerel-agent.conf
    src: mackerel-agent.conf.j2
  notify:
    - Restart mackerel-agent
